name: utopia_injector
description: Utopia libs - Injector
version: 0.0.3
homepage: https://github.com/Utopia-USS/utopia-flutter

environment:
  sdk: ">=3.3.0 <4.0.0"

dev_dependencies:
  utopia_lints: ^0.0.5