name: utopia_hooks_riverpod
description: Utopia Hooks - Riverpod interoperability
version: 0.0.5+2
homepage: https://github.com/Utopia-USS/utopia-flutter

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  utopia_hooks: ^0.4.19+2

  flutter_riverpod: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  utopia_lints: ^0.0.4+1
