name: utopia_hooks_example
description: Demonstrates how to use the utopia_hooks package.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  utopia_hooks:
    path: ../

  utopia_validation:
    path: ../../validation

  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.0

  utopia_lints: ^0.0.3+2

flutter:
  uses-material-design: true
