name: utopia_hooks
description: A comprehensive but flexible state management solution inspired by React Hooks.
version: 0.4.19+1
repository: https://github.com/Utopia-USS/utopia-flutter/tree/master/packages/hooks
documentation: https://hooks.utopiasoft.io
topics:
  - state
  - state-management
  - flutter
  - architecture
  - reactive

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  utopia_utils: ^0.3.3
  utopia_collections: ^0.1.1+1
  utopia_validation: ^0.1.0+4

  collection: ^1.18.0
  equatable: ^2.0.3
  async: ^2.5.0
  meta: ^1.10.0

dev_dependencies:
  flutter_test:
      sdk: flutter
  test: ^1.24.9
  utopia_lints: ^0.0.4+1