name: utopia_platform_utils
description: Utopia USS - Android and iOS platform code utils
version: 0.0.1
homepage: https://github.com/Utopia-USS/utopia-flutter

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  utopia_lints: ^0.0.3+2

flutter:
  plugin:
    platforms:
      android:
        package: com.utopiaultimate.flutter.utopia_platform_utils
        pluginClass: UtopiaPlatformUtilsPlugin
      ios:
        pluginClass: UtopiaPlatformUtilsPlugin
