name: utopia_connectivity
description: Utopia USS libs - ConnectivityState
version: 0.1.0+57
homepage: https://github.com/Utopia-USS/utopia-flutter

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  utopia_arch: ^0.5.1+16
  connectivity_plus: ^6.0.2

dev_dependencies:
  utopia_lints: ^0.0.5