name: utopia_save_file_example
description: Demonstrates how to use the utopia_save_file plugin.
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  utopia_save_file:
    path: ../

  cross_file: ^0.3.3+4
  path_provider: ^2.1.0
  mime: ^1.0.4
  web: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

dependency_overrides:
  utopia_platform_utils:
    path: ../../platform_utils

flutter:
  uses-material-design: true
