name: utopia_save_file_example
description: Demonstrates how to use the utopia_save_file plugin.
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  utopia_save_file:
    path: ../

  cross_file:
  path_provider:
  mime:
  web:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

dependency_overrides:
  utopia_platform_utils:
    path: ../../platform_utils

flutter:
  uses-material-design: true
