name: utopia_bytes
description: Utopia libs - bytes
version: 0.1.0
homepage: https://github.com/Utopia-USS/utopia-flutter

environment:
  sdk: ">=3.1.0 <4.0.0"

dev_dependencies:
  utopia_lints: ^0.0.3+2